import type { ConsumedMessage, MessageExportFormat, TopicSummary } from "../../../../shared/types";
import type { AppLanguage } from "../../../i18n";
import type { MapFieldMapping } from "../../../mapPreview";
import type { ReplayDraft, ReplayPayloadOptions, ReplayTargetServer } from "../../../replayTypes";
import type { ConsumeFilterField, ConsumeFilterMode, ConsumeMode, MessageInspectorMode, OffsetOrder, TopicConsumeState } from "../../../uiTypes";

export type ConsumePanelProps = {
  messages: ConsumedMessage[];
  serverId: string;
  serverName: string;
  topic: string;
  topics: TopicSummary[];
  replayTargets: ReplayTargetServer[];
  language: AppLanguage;
  selectedMessage: ConsumedMessage | null;
  mode: ConsumeMode;
  offsetOrder: OffsetOrder;
  isConsuming: boolean;
  offset: string;
  limit: number;
  partition: string;
  timeStart: string;
  timeEnd: string;
  filterText: string;
  filterField: ConsumeFilterField;
  filterMode: ConsumeFilterMode;
  inspectorMode: MessageInspectorMode;
  inspectorCollapsed: boolean;
  isQuerying: boolean;
  autoScroll: boolean;
  maxMessages: number;
  liveRecordEnabled: boolean;
  liveRecordPath: string;
  liveRecordCount: number;
  keyFormat: TopicConsumeState["keyFormat"];
  valueFormat: TopicConsumeState["valueFormat"];
  payloadEncoding: TopicConsumeState["payloadEncoding"];
  valueColumnPaths: string[];
  mapFieldMapping: MapFieldMapping | null;
  offsetPagination: TopicConsumeState["offsetPagination"];
  messagePaneHeight: number;
  onMode: (value: ConsumeMode) => void;
  onOffsetOrder: (value: OffsetOrder) => void;
  onOffset: (value: string) => void;
  onLimit: (value: number) => void;
  onPartition: (value: string) => void;
  onTimeStart: (value: string) => void;
  onTimeEnd: (value: string) => void;
  onFilterText: (value: string) => void;
  onFilterField: (value: ConsumeFilterField) => void;
  onFilterMode: (value: ConsumeFilterMode) => void;
  onInspectorMode: (value: MessageInspectorMode) => void;
  onInspectorCollapsed: (value: boolean) => void;
  onClearFilter: () => void;
  onApplyFilter: (value: string) => void;
  onAutoScroll: (value: boolean) => void;
  onMaxMessages: (value: number) => void;
  onLiveRecordEnabled: (value: boolean) => void;
  onKeyFormat: (value: TopicConsumeState["keyFormat"]) => void;
  onValueFormat: (value: TopicConsumeState["valueFormat"]) => void;
  onPayloadEncoding: (value: TopicConsumeState["payloadEncoding"]) => void;
  onValueColumnPaths: (value: string[]) => void;
  onMapFieldMapping: (value: MapFieldMapping | null) => void;
  onPagePrev: () => void;
  onPageNext: () => void;
  onSelectMessage: (message: ConsumedMessage) => void;
  onMessagePaneHeight: (value: number) => void;
  onSendToProduce: (message: ConsumedMessage, targetTopic?: string, targetServerId?: string, payload?: ReplayPayloadOptions) => void;
  onReplayMessage: (serverId: string, topic: string, draft: ReplayDraft) => Promise<void>;
  onConnectReplayServer: (serverId: string) => Promise<boolean>;
  onExport: (format: MessageExportFormat, messages: ConsumedMessage[]) => void;
  onExportAll: (format: MessageExportFormat) => void;
  onStart: () => void;
  onStop: () => void;
};
