import type { AppMenuLanguage } from "../shared/types.js";

function joinHelp(lines: string[]) {
  return lines.join("\n");
}

export const menuText = {
  ko: {
    file: "파일",
    importSettings: "설정 가져오기...",
    exportSettings: "설정 내보내기...",
    preferences: "환경설정...",
    avroSchemas: "Avro Schemas...",
    checkUpdates: "업데이트 확인...",
    close: "닫기",
    quit: "종료",
    importTitle: "설정 가져오기",
    importMessage: "현재 서버 목록과 환경설정을 가져온 파일로 교체할까요?",
    importButton: "가져오기",
    cancelButton: "취소",
    help: "도움말",
    shortcuts: "단축키",
    splitTabs: "탭 분할",
    searchTips: "검색과 필터",
    kafkaTips: "Kafka 작업 팁",
    produceTips: "Produce",
    viewerTips: "Message Viewer",
    recordTips: "Live Record",
    releaseNotes: "Release Notes",
    about: "KafkaPilot 정보",
    helpOk: "확인",
    helpShortcutsTitle: "단축키",
    helpShortcutsMessage: joinHelp([
      "빠른 이동",
      "  Ctrl+P / Ctrl+K  Quick Search 열기",
      "  ↑ / ↓            검색 결과 이동",
      "  Enter            선택한 결과 열기",
      "  Esc              검색 또는 팝업 닫기",
      "",
      "탭 분할",
      "  Ctrl/Cmd+→       현재 Topic을 오른쪽 pane으로 보내기",
      "  Ctrl/Cmd+←       오른쪽 pane의 현재 Topic을 왼쪽 pane으로 보내기",
      "  Ctrl/Cmd+1       왼쪽 pane 활성화",
      "  Ctrl/Cmd+2       오른쪽 pane 활성화",
      "  Ctrl/Cmd+W       현재 Topic 탭 닫기",
      "  Ctrl/Cmd+Shift+W split pane 닫기",
      "",
      "단축키 편집",
      "  환경설정 > Editor > Shortcuts에서 앱 내부 단축키를 변경할 수 있습니다.",
      "  Mod는 macOS에서는 Cmd, Windows/Linux에서는 Ctrl로 동작합니다.",
      "  입력창 안에서는 split 관련 단축키가 실행되지 않습니다.",
      "",
      "설정",
      "  Ctrl+O           설정 파일 가져오기",
      "  Ctrl+S           설정 파일 내보내기",
      "  Ctrl+,           환경설정 열기",
      "",
      "팁",
      "  Topic, Consumer Group, Broker 행을 클릭하면 상세 화면으로 이동합니다.",
      "  Topic/Server는 우클릭 메뉴로 자주 쓰는 작업을 바로 실행할 수 있습니다."
    ]),
    helpSplitTitle: "탭 분할",
    helpSplitMessage: joinHelp([
      "분할 열기",
      "  Cluster 탭이나 Topic 탭을 작업 영역으로 드래그하면 좌우 분할 pane을 만들 수 있습니다.",
      "  현재 Topic에서는 Ctrl/Cmd+→ 단축키로 바로 오른쪽 pane을 열 수 있습니다.",
      "  오른쪽 pane에서는 Ctrl/Cmd+← 단축키로 현재 Topic을 왼쪽 pane으로 옮길 수 있습니다.",
      "  단축키는 환경설정 > Editor > Shortcuts에서 변경할 수 있습니다.",
      "  같은 서버 안에서 Topic Info, Consume, Produce, Settings를 나란히 볼 때 유용합니다.",
      "",
      "분할 닫기",
      "  탭을 분할 닫기 영역으로 드롭하면 split pane이 닫힙니다.",
      "  Ctrl/Cmd+Shift+W 단축키로도 split pane을 닫을 수 있습니다.",
      "  서버별 split 상태는 서로 독립적으로 유지됩니다.",
      "",
      "크기 조절",
      "  좌우 pane 사이의 경계선을 드래그해 폭을 조절할 수 있습니다.",
      "  Consume 화면에서는 메시지 그리드와 Message Viewer 사이의 경계선도 드래그할 수 있습니다."
    ]),
    helpSearchTitle: "검색과 필터",
    helpSearchMessage: joinHelp([
      "Quick Search",
      "  topic-name              Topic, 열린 탭, Consumer Group, Server를 검색합니다.",
      "  @\"Server Name\" topic    특정 서버 안에서 Topic을 검색합니다.",
      "  >topic delete name      확인 후 Topic 삭제 명령을 실행합니다.",
      "  >topic purge name       확인 후 Topic 메시지 비우기를 실행합니다.",
      "",
      "Topics 검색",
      "  word another            공백은 AND 조건입니다.",
      "  -word                   특정 단어를 제외합니다.",
      "  /pattern/i              정규식으로 검색합니다.",
      "",
      "Consume 필터",
      "  key:PR1001              Key에서 검색합니다.",
      "  value:OK                Value에서 검색합니다.",
      "  headers.traceId exists  Header 존재 여부를 확인합니다.",
      "  decoded.speed >= 80     JSON/Avro decoded 값 비교를 지원합니다.",
      "  !error -timeout         제외 조건을 적용합니다."
    ]),
    helpKafkaTitle: "Kafka 작업 팁",
    helpKafkaMessage: joinHelp([
      "Topics",
      "  Topic 우클릭 메뉴에서 Open, Copy name, Register Avro Schema, Purge, Delete를 실행할 수 있습니다.",
      "  Clear messages는 Topic은 유지하고 현재 high offset까지 record를 비웁니다.",
      "  Delete Topic은 클러스터에서 Topic 자체를 삭제하므로 주의하세요.",
      "",
      "Settings",
      "  Topic Settings는 Kafka가 editable로 알려준 config만 수정 대상으로 다룹니다.",
      "  Custom parameter는 Kafka Topic config 이름을 선택한 뒤 값을 입력해 추가합니다.",
      "",
      "Consumer Groups",
      "  Consumer Group 상세는 Topic별로 접고 펼치며 Lag, Current Offset, End Offset을 확인할 수 있습니다.",
      "  실행 중인 group은 Kafka 정책에 따라 삭제가 거부될 수 있습니다."
    ]),
    helpProduceTitle: "Produce",
    helpProduceMessage: joinHelp([
      "발행 모드",
      "  Single은 현재 Key, Headers, Value를 한 번 발행합니다.",
      "  Interval은 Every 간격으로 반복 발행하며 Count 또는 Duration 제한이 반드시 필요합니다.",
      "  무제한 발행은 제공하지 않으며, 시작 전 Topic, Every, 제한 조건을 다시 확인합니다.",
      "",
      "동적 필드",
      "  Key, Headers, Value에서 같은 동적 필드 문법을 사용할 수 있습니다.",
      "  ${seq}                         1부터 증가하는 시퀀스",
      "  VMS${seq:1..100|pad=7}         VMS0000001 형태의 순차 ID",
      "  ${random:1..100}               범위 내 정수 랜덤",
      "  ${float:0..1|fixed=2}          소수점 자릿수 제한 랜덤",
      "  ${choice:READY|RUNNING|ERROR}  목록 중 하나 선택",
      "  ${date:yyyy-MM-dd HH:mm:ss}    지역 날짜/시간 문자열",
      "  ${timestamp} / ${timestamp:s}  epoch milliseconds / seconds",
      "  ${uuid}                        UUID v4",
      "  \\${uuid}                       치환하지 않고 문자 그대로 전송",
      "",
      "Preview와 템플릿",
      "  Preview는 발행 전 렌더링된 Key, Headers, Value를 확인합니다.",
      "  잘못된 동적 필드는 Preview에 표시되고 Interval 시작이 차단됩니다.",
      "  Produce Template은 Topic별로 저장되며 설정 내보내기/가져오기에 포함됩니다."
    ]),
    helpViewerTitle: "Message Viewer",
    helpViewerMessage: joinHelp([
      "보기 모드",
      "  Raw       선택한 메시지를 JSON 형태로 확인합니다.",
      "  Tree      구조화 가능한 payload를 접고 펼쳐서 확인합니다.",
      "  Preview   Key, Value, Headers, Message를 원하는 포맷으로 확인합니다.",
      "",
      "Payload 포맷",
      "  Text      UTF-8 또는 EUC-KR로 디코딩합니다.",
      "  JSON      decoded Value 또는 JSON 문자열을 보기 좋게 표시합니다.",
      "  Hex       raw bytes를 hex로 표시합니다.",
      "  Base64    raw bytes를 base64로 표시합니다.",
      "",
      "메모리 보호",
      "  큰 payload는 raw bytes 보관이 제한될 수 있습니다.",
      "  이 경우 Text는 볼 수 있지만 Hex/Base64에는 raw 보관 제한 안내가 표시됩니다."
    ]),
    helpRecordTitle: "Live Record",
    helpRecordMessage: joinHelp([
      "Record 사용",
      "  Consume Live 모드에서 Record를 켜고 시작하면 저장 경로를 선택합니다.",
      "  수신되는 메시지는 JSONL 파일에 한 줄씩 기록됩니다.",
      "",
      "종료 시점",
      "  Live 중지, Topic 탭 닫기, 서버 연결 해제, 앱 종료 시점까지 기록된 내용은 파일에 남습니다.",
      "  장시간 수집은 UI 메모리가 아니라 파일 스트림으로 처리됩니다.",
      "",
      "운영 팁",
      "  대량 수집은 Record를 사용하고, UI에는 필요한 max messages만 유지하는 것을 권장합니다.",
      "  파일 쓰기 속도보다 수신 속도가 빠른 경우 내부적으로 쓰기 순서를 기다려 메모리 증가를 줄입니다."
    ]),
    aboutTitle: "KafkaPilot 정보",
    aboutMessage: joinHelp([
      "KafkaPilot desktop client",
      "",
      "Broker, Topic, Consumer Group, Produce, Consume, Avro, Record 작업을 한 곳에서 관리합니다.",
      "GitHub Releases 기반 자동 업데이트와 Windows/macOS 패키징을 지원합니다."
    ]),
    saveLiveRecord: "Live Record 저장"
  },
  en: {
    file: "File",
    importSettings: "Import Settings...",
    exportSettings: "Export Settings...",
    preferences: "Preferences...",
    avroSchemas: "Avro Schemas...",
    checkUpdates: "Check for Updates...",
    close: "Close",
    quit: "Quit",
    importTitle: "Import Settings",
    importMessage: "Replace the current server list and preferences with the imported file?",
    importButton: "Import",
    cancelButton: "Cancel",
    help: "Help",
    shortcuts: "Shortcuts",
    splitTabs: "Split tabs",
    searchTips: "Search and filters",
    kafkaTips: "Kafka work tips",
    produceTips: "Produce",
    viewerTips: "Message Viewer",
    recordTips: "Live Record",
    releaseNotes: "Release Notes",
    about: "About KafkaPilot",
    helpOk: "OK",
    helpShortcutsTitle: "Shortcuts",
    helpShortcutsMessage: joinHelp([
      "Navigation",
      "  Ctrl+P / Ctrl+K  Open Quick Search",
      "  Up / Down         Move through search results",
      "  Enter             Open the selected result",
      "  Esc               Close search or popovers",
      "",
      "Split tabs",
      "  Ctrl/Cmd+Right   Send the current Topic to the right pane",
      "  Ctrl/Cmd+Left    Send the current Topic in the right pane to the left pane",
      "  Ctrl/Cmd+1       Focus the left pane",
      "  Ctrl/Cmd+2       Focus the right pane",
      "  Ctrl/Cmd+W       Close the current Topic tab",
      "  Ctrl/Cmd+Shift+W Close the split pane",
      "",
      "Custom shortcuts",
      "  Change in Preferences > Editor > Shortcuts.",
      "  Mod means Cmd on macOS and Ctrl on Windows/Linux.",
      "  Split shortcuts are ignored while typing in inputs.",
      "",
      "Settings",
      "  Ctrl+O            Import settings",
      "  Ctrl+S            Export settings",
      "  Ctrl+,            Open Preferences",
      "",
      "Tips",
      "  Click Topic, Consumer Group, or Broker rows to open details.",
      "  Use Topic and Server context menus for common actions."
    ]),
    helpSplitTitle: "Split tabs",
    helpSplitMessage: joinHelp([
      "Open split panes",
      "  Drag a Cluster tab or Topic tab into the workspace to split the view.",
      "  Press Ctrl/Cmd+Right on a Topic to open it directly in the right pane.",
      "  Press Ctrl/Cmd+Left in the right pane to move the current Topic back to the left pane.",
      "  You can change this shortcut in Preferences > Editor > Shortcuts.",
      "  This is useful for viewing Topic Info, Consume, Produce, and Settings side by side.",
      "",
      "Close split panes",
      "  Drop a tab onto the close split drop zone to close the split pane.",
      "  Press Ctrl/Cmd+Shift+W to close the split pane from the keyboard.",
      "  Split pane state is kept independently per server.",
      "",
      "Resize",
      "  Drag the divider between panes to resize the split.",
      "  In Consume, drag the divider between the message grid and Message Viewer."
    ]),
    helpSearchTitle: "Search and filters",
    helpSearchMessage: joinHelp([
      "Quick Search",
      "  topic-name              Search Topics, open tabs, Consumer Groups, and Servers.",
      "  @\"Server Name\" topic    Search Topics inside one server.",
      "  >topic delete name      Delete a Topic after confirmation.",
      "  >topic purge name       Clear Topic messages after confirmation.",
      "",
      "Topics search",
      "  word another            Spaces mean AND.",
      "  -word                   Exclude a word.",
      "  /pattern/i              Search with regex.",
      "",
      "Consume filters",
      "  key:PR1001              Search in Key.",
      "  value:OK                Search in Value.",
      "  headers.traceId exists  Check Header existence.",
      "  decoded.speed >= 80     Compare decoded JSON/Avro values.",
      "  !error -timeout         Apply exclusion conditions."
    ]),
    helpKafkaTitle: "Kafka work tips",
    helpKafkaMessage: joinHelp([
      "Topics",
      "  Topic context menus can Open, Copy name, Register Avro Schema, Purge, or Delete.",
      "  Clear messages keeps the Topic and removes records up to current high offsets.",
      "  Delete Topic removes the Topic from the cluster, so use it carefully.",
      "",
      "Settings",
      "  Topic Settings edits only configs Kafka reports as editable.",
      "  Custom parameters add Kafka Topic config names with values.",
      "",
      "Consumer Groups",
      "  Consumer Group details expand by Topic to inspect Lag, Current Offset, and End Offset.",
      "  Kafka may reject deleting groups that are currently running."
    ]),
    helpProduceTitle: "Produce",
    helpProduceMessage: joinHelp([
      "Produce modes",
      "  Single sends the current Key, Headers, and Value once.",
      "  Interval repeats sends by Every and requires either Count or Duration.",
      "  Unlimited sending is not available, and Topic, Every, and limits are confirmed before start.",
      "",
      "Dynamic fields",
      "  Key, Headers, and Value support the same dynamic field syntax.",
      "  ${seq}                         Sequence starting at 1",
      "  VMS${seq:1..100|pad=7}         Sequential IDs such as VMS0000001",
      "  ${random:1..100}               Random integer in range",
      "  ${float:0..1|fixed=2}          Random float with fixed decimals",
      "  ${choice:READY|RUNNING|ERROR}  Pick one item from a list",
      "  ${date:yyyy-MM-dd HH:mm:ss}    Local date/time string",
      "  ${timestamp} / ${timestamp:s}  Epoch milliseconds / seconds",
      "  ${uuid}                        UUID v4",
      "  \\${uuid}                       Send the literal text without replacement",
      "",
      "Preview and templates",
      "  Preview shows the rendered Key, Headers, and Value before sending.",
      "  Invalid dynamic fields are shown in Preview and block Interval start.",
      "  Produce Templates are stored per Topic and included in settings import/export."
    ]),
    helpViewerTitle: "Message Viewer",
    helpViewerMessage: joinHelp([
      "View modes",
      "  Raw       Inspect the selected message as JSON.",
      "  Tree      Expand structured payloads.",
      "  Preview   Inspect Key, Value, Headers, or Message in a chosen format.",
      "",
      "Payload formats",
      "  Text      Decode with UTF-8 or EUC-KR.",
      "  JSON      Pretty print decoded Value or JSON text.",
      "  Hex       Show raw bytes as hex.",
      "  Base64    Show raw bytes as base64.",
      "",
      "Memory protection",
      "  Large payload raw bytes may not be retained.",
      "  Text can still be shown, but Hex/Base64 will display a retained-bytes warning."
    ]),
    helpRecordTitle: "Live Record",
    helpRecordMessage: joinHelp([
      "Using Record",
      "  Enable Record in Consume Live mode and choose a save path when Live starts.",
      "  Incoming messages are written as JSONL, one message per line.",
      "",
      "Stop points",
      "  Data written up to Live stop, Topic tab close, server disconnect, or app exit remains in the file.",
      "  Long-running captures are handled through a file stream instead of renderer memory.",
      "",
      "Operations tip",
      "  Use Record for large captures and keep only the required max messages in the UI.",
      "  If writes are slower than incoming messages, writes are awaited in order to reduce memory growth."
    ]),
    aboutTitle: "About KafkaPilot",
    aboutMessage: joinHelp([
      "KafkaPilot desktop client",
      "",
      "Manage Broker, Topic, Consumer Group, Produce, Consume, Avro, and Record workflows in one place.",
      "Supports GitHub Releases based auto updates and Windows/macOS packaging."
    ]),
    saveLiveRecord: "Save Live Record"
  }
} satisfies Record<AppMenuLanguage, Record<string, string>>;
